---
abstract: 'Parallelizing Edlib with MCE, OpenMP using Inline and FFI::Platypus'
author:
  - 'Christos Argyropoulos <chrisarg@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.032, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Bio-SeqAlignment-Examples-EnhancingEdlib
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  Bio::SeqAlignment::Examples::EnhancingEdlib:
    file: lib/Bio/SeqAlignment/Examples/EnhancingEdlib.pm
    version: '0.01'
requires:
  strict: '0'
  warnings: '0'
version: '0.01'
x_generated_by_perl: v5.38.0
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
